#!/usr/bin/env python3
import re
import sys
import urllib.request
from pathlib import Path

UPSTREAM = "https://raw.githubusercontent.com/shirriff/Arduino-TV-B-Gone/master/WORLD_IR_CODES.h"

def parse_numbers(body):
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = re.sub(r"//.*", "", body)
    out = []
    for token in body.split(","):
        token = token.strip()
        if not token:
            continue
        out.append(int(token, 0))
    return out

def strip_comments(s):
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    s = re.sub(r"//.*", "", s)
    return s

def read_bits(data, nbits, bitpos):
    value = 0
    for _ in range(nbits):
        byte_index = bitpos // 8
        bit_index = 7 - (bitpos % 8)
        bit = (data[byte_index] >> bit_index) & 1
        value = (value << 1) | bit
        bitpos += 1
    return value, bitpos

def main():
    if len(sys.argv) >= 2 and Path(sys.argv[1]).exists():
        text = Path(sys.argv[1]).read_text(encoding="utf-8")
        output = Path(sys.argv[2]) if len(sys.argv) >= 3 else Path("Sources/GeneratedTVBGoneDatabase.swift")
    else:
        with urllib.request.urlopen(UPSTREAM, timeout=30) as response:
            text = response.read().decode("utf-8")
        output = Path(sys.argv[1]) if len(sys.argv) >= 2 else Path("Sources/GeneratedTVBGoneDatabase.swift")

    timing_arrays = {}
    for m in re.finditer(r"const\s+uint16_t\s+(\w+Times)\[\]\s+PROGMEM\s*=\s*\{(.*?)\};", text, re.S):
        timing_arrays[m.group(1)] = parse_numbers(m.group(2))

    code_arrays = {}
    for m in re.finditer(r"const\s+uint8_t\s+(\w+Codes)\[\]\s+PROGMEM\s*=\s*\{(.*?)\};", text, re.S):
        code_arrays[m.group(1)] = parse_numbers(m.group(2))

    structs = {}
    pattern = re.compile(
        r"const\s+struct\s+IrCode\s+(\w+Code)\s+PROGMEM\s*=\s*\{\s*"
        r"(freq_to_timerval\((\d+)\)|0)\s*,\s*"
        r"(\d+)\s*,.*?"
        r"(\d+)\s*,.*?"
        r"(\w+Times)\s*,\s*"
        r"(\w+Codes)\s*\};",
        re.S,
    )

    for m in pattern.finditer(text):
        name = m.group(1)
        carrier = int(m.group(3)) if m.group(3) else 0
        numpairs = int(m.group(4))
        bitcompression = int(m.group(5))
        times_name = m.group(6)
        codes_name = m.group(7)

        times = timing_arrays[times_name]
        packed = code_arrays[codes_name]
        bitpos = 0
        durations = []
        for _ in range(numpairs):
            idx, bitpos = read_bits(packed, bitcompression, bitpos)
            pos = idx * 2
            if pos + 1 >= len(times):
                raise RuntimeError(f"Timing index out of range in {name}")
            durations.extend((times[pos] * 10, times[pos + 1] * 10))
        structs[name] = (carrier, durations)

    def region(name):
        m = re.search(
            rf"const\s+IrCode\*\s+const\s+{name}\[\]\s+PROGMEM\s*=\s*\{{(.*?)\}};",
            text,
            re.S,
        )
        if not m:
            raise RuntimeError(f"Missing region {name}")
        body = strip_comments(m.group(1))
        names = re.findall(r"&\s*(\w+Code)", body)
        return names

    na_names = region("NApowerCodes")
    eu_names = region("EUpowerCodes")

    missing = [n for n in na_names + eu_names if n not in structs]
    if missing:
        raise RuntimeError("Unparsed codes: " + ", ".join(missing[:10]))

    def swift_array(names):
        lines = []
        for name in names:
            carrier, durations = structs[name]
            nums = ",".join(str(x) for x in durations)
            lines.append(
                f'        IRCode(id: "{name}", carrierHz: {carrier}, durationsMicros: [{nums}]),'
            )
        return "\n".join(lines)

    swift = """// AUTO-GENERATED by scripts/generate_database.py
// Source database: Arduino-TV-B-Gone / WORLD_IR_CODES.h
// Original TV-B-Gone firmware data © Mitch Altman + Limor Fried (2009)
// Distributed upstream under CC BY-SA 2.5.

import Foundation

enum GeneratedTVBGoneDatabase {
    static let northAmerica: [IRCode] = [
%s
    ]

    static let europe: [IRCode] = [
%s
    ]
}
""" % (swift_array(na_names), swift_array(eu_names))

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(swift, encoding="utf-8")
    print(f"Generated {len(na_names)} NA codes and {len(eu_names)} EU codes -> {output}")

if __name__ == "__main__":
    main()
